import io.circe.parser._
import io.circe.generic.auto._
import org.scalatest.FunSpec
import org.scalatest.Matchers._
import twitter4s.{UserArray, UserStatus}

/**
  * Created by lrf141 on 17/09/23.
  */
class FollowersListGetTest extends FunSpec{

  describe("Followers get test"){

    it("main test"){
      val json:String = """ {
                          |  "users": [
                          |    {
                          |      "id": 2960784075,
                          |      "id_str": "2960784075",
                          |      "name": "Jesus Rafael Abreu M",
                          |      "screen_name": "chuomaraver",
                          |      "location": "",
                          |      "profile_location": null,
                          |      "url": null,
                          |      "description": "",
                          |      "protected": false,
                          |      "followers_count": 1,
                          |      "friends_count": 101,
                          |      "listed_count": 0,
                          |      "created_at": "Sun Jan 04 19:58:06 +0000 2015",
                          |      "favourites_count": 0,
                          |      "utc_offset": null,
                          |      "time_zone": null,
                          |      "geo_enabled": false,
                          |      "verified": false,
                          |      "statuses_count": 0,
                          |      "lang": "es",
                          |      "contributors_enabled": false,
                          |      "is_translator": false,
                          |      "is_translation_enabled": false,
                          |      "profile_background_color": "C0DEED",
                          |      "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png",
                          |      "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png",
                          |      "profile_background_tile": false,
                          |      "profile_image_url": "http://abs.twimg.com/sticky/default_profile_images/default_profile_4_normal.png",
                          |      "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_4_normal.png",
                          |      "profile_link_color": "0084B4",
                          |      "profile_sidebar_border_color": "C0DEED",
                          |      "profile_sidebar_fill_color": "DDEEF6",
                          |      "profile_text_color": "333333",
                          |      "profile_use_background_image": true,
                          |      "default_profile": true,
                          |      "default_profile_image": true,
                          |      "following": false,
                          |      "follow_request_sent": false,
                          |      "notifications": false,
                          |      "muting": false
                          |    },
                          |    {
                          |      "id": 2959453074,
                          |      "id_str": "2959453074",
                          |      "name": "lama masarwa",
                          |      "screen_name": "LamaMasarwa",
                          |      "location": "",
                          |      "profile_location": null,
                          |      "url": null,
                          |      "description": "",
                          |      "protected": false,
                          |      "followers_count": 7,
                          |      "friends_count": 53,
                          |      "listed_count": 0,
                          |      "created_at": "Mon Jan 05 10:10:46 +0000 2015",
                          |      "favourites_count": 0,
                          |      "utc_offset": null,
                          |      "time_zone": null,
                          |      "geo_enabled": false,
                          |      "verified": false,
                          |      "statuses_count": 2,
                          |      "lang": "he",
                          |      "contributors_enabled": false,
                          |      "is_translator": false,
                          |      "is_translation_enabled": false,
                          |      "profile_background_color": "C0DEED",
                          |      "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png",
                          |      "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png",
                          |      "profile_background_tile": false,
                          |      "profile_image_url": "http://pbs.twimg.com/profile_images/552047388873859072/itk5cPx6_normal.png",
                          |      "profile_image_url_https": "https://pbs.twimg.com/profile_images/552047388873859072/itk5cPx6_normal.png",
                          |      "profile_banner_url": "https://pbs.twimg.com/profile_banners/2959453074/1420454122",
                          |      "profile_link_color": "0084B4",
                          |      "profile_sidebar_border_color": "C0DEED",
                          |      "profile_sidebar_fill_color": "DDEEF6",
                          |      "profile_text_color": "333333",
                          |      "profile_use_background_image": true,
                          |      "default_profile": true,
                          |      "default_profile_image": false,
                          |      "following": false,
                          |      "follow_request_sent": false,
                          |      "notifications": false,
                          |      "muting": false
                          |    },
                          |    {
                          |      "id": 2962184776,
                          |      "id_str": "2962184776",
                          |      "name": "elkholfi khaola",
                          |      "screen_name": "ElkholfiKhaoula",
                          |      "location": "",
                          |      "profile_location": null,
                          |      "url": null,
                          |      "description": "",
                          |      "protected": false,
                          |      "followers_count": 4,
                          |      "friends_count": 115,
                          |      "listed_count": 0,
                          |      "created_at": "Mon Jan 05 14:42:54 +0000 2015",
                          |      "favourites_count": 0,
                          |      "utc_offset": null,
                          |      "time_zone": null,
                          |      "geo_enabled": false,
                          |      "verified": false,
                          |      "statuses_count": 0,
                          |      "lang": "fr",
                          |      "contributors_enabled": false,
                          |      "is_translator": false,
                          |      "is_translation_enabled": false,
                          |      "profile_background_color": "C0DEED",
                          |      "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png",
                          |      "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png",
                          |      "profile_background_tile": false,
                          |      "profile_image_url": "http://abs.twimg.com/sticky/default_profile_images/default_profile_5_normal.png",
                          |      "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_5_normal.png",
                          |      "profile_link_color": "0084B4",
                          |      "profile_sidebar_border_color": "C0DEED",
                          |      "profile_sidebar_fill_color": "DDEEF6",
                          |      "profile_text_color": "333333",
                          |      "profile_use_background_image": true,
                          |      "default_profile": true,
                          |      "default_profile_image": true,
                          |      "following": false,
                          |      "follow_request_sent": false,
                          |      "notifications": false,
                          |      "muting": false
                          |    },
                          |    {
                          |      "id": 2959764566,
                          |      "id_str": "2959764566",
                          |      "name": "Brando",
                          |      "screen_name": "BrandoBb19",
                          |      "location": "",
                          |      "profile_location": null,
                          |      "url": null,
                          |      "description": "",
                          |      "protected": false,
                          |      "followers_count": 5,
                          |      "friends_count": 214,
                          |      "listed_count": 0,
                          |      "created_at": "Mon Jan 05 14:28:49 +0000 2015",
                          |      "favourites_count": 0,
                          |      "utc_offset": null,
                          |      "time_zone": null,
                          |      "geo_enabled": false,
                          |      "verified": false,
                          |      "statuses_count": 1,
                          |      "lang": "en-AU",
                          |      "contributors_enabled": false,
                          |      "is_translator": false,
                          |      "is_translation_enabled": false,
                          |      "profile_background_color": "C0DEED",
                          |      "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png",
                          |      "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png",
                          |      "profile_background_tile": false,
                          |      "profile_image_url": "http://pbs.twimg.com/profile_images/552113782160252928/JxnwvMaC_normal.jpeg",
                          |      "profile_image_url_https": "https://pbs.twimg.com/profile_images/552113782160252928/JxnwvMaC_normal.jpeg",
                          |      "profile_banner_url": "https://pbs.twimg.com/profile_banners/2959764566/1420469158",
                          |      "profile_link_color": "0084B4",
                          |      "profile_sidebar_border_color": "C0DEED",
                          |      "profile_sidebar_fill_color": "DDEEF6",
                          |      "profile_text_color": "333333",
                          |      "profile_use_background_image": true,
                          |      "default_profile": true,
                          |      "default_profile_image": false,
                          |      "following": false,
                          |      "follow_request_sent": false,
                          |      "notifications": false,
                          |      "muting": false
                          |    },
                          |    {
                          |      "id": 2959474814,
                          |      "id_str": "2959474814",
                          |      "name": "Atank suhenda",
                          |      "screen_name": "Atank009",
                          |      "location": "",
                          |      "profile_location": null,
                          |      "url": null,
                          |      "description": "",
                          |      "protected": false,
                          |      "followers_count": 12,
                          |      "friends_count": 279,
                          |      "listed_count": 0,
                          |      "created_at": "Mon Jan 05 09:52:00 +0000 2015",
                          |      "favourites_count": 0,
                          |      "utc_offset": 10800,
                          |      "time_zone": "Nairobi",
                          |      "geo_enabled": false,
                          |      "verified": false,
                          |      "statuses_count": 1,
                          |      "lang": "id",
                          |      "contributors_enabled": false,
                          |      "is_translator": false,
                          |      "is_translation_enabled": false,
                          |      "profile_background_color": "C0DEED",
                          |      "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png",
                          |      "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png",
                          |      "profile_background_tile": false,
                          |      "profile_image_url": "http://pbs.twimg.com/profile_images/552041513400545282/eXUV9Rs8_normal.jpeg",
                          |      "profile_image_url_https": "https://pbs.twimg.com/profile_images/552041513400545282/eXUV9Rs8_normal.jpeg",
                          |      "profile_banner_url": "https://pbs.twimg.com/profile_banners/2959474814/1420468612",
                          |      "profile_link_color": "0084B4",
                          |      "profile_sidebar_border_color": "C0DEED",
                          |      "profile_sidebar_fill_color": "DDEEF6",
                          |      "profile_text_color": "333333",
                          |      "profile_use_background_image": true,
                          |      "default_profile": true,
                          |      "default_profile_image": false,
                          |      "following": false,
                          |      "follow_request_sent": false,
                          |      "notifications": false,
                          |      "muting": false
                          |    },
                          |    {
                          |      "id": 2962030155,
                          |      "id_str": "2962030155",
                          |      "name": "Андрей Лазарев",
                          |      "screen_name": "hausrus",
                          |      "location": "",
                          |      "profile_location": null,
                          |      "url": null,
                          |      "description": "",
                          |      "protected": false,
                          |      "followers_count": 18,
                          |      "friends_count": 191,
                          |      "listed_count": 0,
                          |      "created_at": "Mon Jan 05 13:41:28 +0000 2015",
                          |      "favourites_count": 0,
                          |      "utc_offset": null,
                          |      "time_zone": null,
                          |      "geo_enabled": false,
                          |      "verified": false,
                          |      "statuses_count": 2,
                          |      "lang": "ru",
                          |      "contributors_enabled": false,
                          |      "is_translator": false,
                          |      "is_translation_enabled": false,
                          |      "profile_background_color": "C0DEED",
                          |      "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png",
                          |      "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png",
                          |      "profile_background_tile": false,
                          |      "profile_image_url": "http://pbs.twimg.com/profile_images/552098040828264448/2RdQDKRP_normal.jpeg",
                          |      "profile_image_url_https": "https://pbs.twimg.com/profile_images/552098040828264448/2RdQDKRP_normal.jpeg",
                          |      "profile_link_color": "0084B4",
                          |      "profile_sidebar_border_color": "C0DEED",
                          |      "profile_sidebar_fill_color": "DDEEF6",
                          |      "profile_text_color": "333333",
                          |      "profile_use_background_image": true,
                          |      "default_profile": true,
                          |      "default_profile_image": false,
                          |      "following": false,
                          |      "follow_request_sent": false,
                          |      "notifications": false,
                          |      "muting": false
                          |    },
                          |    {
                          |      "id": 2961113165,
                          |      "id_str": "2961113165",
                          |      "name": "Nathalia Dhiovane",
                          |      "screen_name": "71559af524da491",
                          |      "location": "",
                          |      "profile_location": null,
                          |      "url": null,
                          |      "description": "",
                          |      "protected": false,
                          |      "followers_count": 22,
                          |      "friends_count": 384,
                          |      "listed_count": 0,
                          |      "created_at": "Sun Jan 04 23:07:58 +0000 2015",
                          |      "favourites_count": 0,
                          |      "utc_offset": null,
                          |      "time_zone": null,
                          |      "geo_enabled": false,
                          |      "verified": false,
                          |      "statuses_count": 0,
                          |      "lang": "pt",
                          |      "contributors_enabled": false,
                          |      "is_translator": false,
                          |      "is_translation_enabled": false,
                          |      "profile_background_color": "C0DEED",
                          |      "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png",
                          |      "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png",
                          |      "profile_background_tile": false,
                          |      "profile_image_url": "http://pbs.twimg.com/profile_images/551879344495534080/JGrpUo0Q_normal.jpeg",
                          |      "profile_image_url_https": "https://pbs.twimg.com/profile_images/551879344495534080/JGrpUo0Q_normal.jpeg",
                          |      "profile_banner_url": "https://pbs.twimg.com/profile_banners/2961113165/1420413259",
                          |      "profile_link_color": "0084B4",
                          |      "profile_sidebar_border_color": "C0DEED",
                          |      "profile_sidebar_fill_color": "DDEEF6",
                          |      "profile_text_color": "333333",
                          |      "profile_use_background_image": true,
                          |      "default_profile": true,
                          |      "default_profile_image": false,
                          |      "following": false,
                          |      "follow_request_sent": false,
                          |      "notifications": false,
                          |      "muting": false
                          |    },
                          |    {
                          |      "id": 472009153,
                          |      "id_str": "472009153",
                          |      "name": "Lorenzo Soffiati",
                          |      "screen_name": "Lory_270",
                          |      "location": "Rizza",
                          |      "profile_location": null,
                          |      "url": null,
                          |      "description": "",
                          |      "protected": false,
                          |      "followers_count": 10,
                          |      "friends_count": 71,
                          |      "listed_count": 0,
                          |      "created_at": "Mon Jan 23 14:08:12 +0000 2012",
                          |      "favourites_count": 5,
                          |      "utc_offset": null,
                          |      "time_zone": null,
                          |      "geo_enabled": false,
                          |      "verified": false,
                          |      "statuses_count": 49,
                          |      "lang": "it",
                          |      "contributors_enabled": false,
                          |      "is_translator": false,
                          |      "is_translation_enabled": false,
                          |      "profile_background_color": "C0DEED",
                          |      "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png",
                          |      "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png",
                          |      "profile_background_tile": false,
                          |      "profile_image_url": "http://pbs.twimg.com/profile_images/423524106307665920/mNxLIIvg_normal.jpeg",
                          |      "profile_image_url_https": "https://pbs.twimg.com/profile_images/423524106307665920/mNxLIIvg_normal.jpeg",
                          |      "profile_banner_url": "https://pbs.twimg.com/profile_banners/472009153/1389811098",
                          |      "profile_link_color": "0084B4",
                          |      "profile_sidebar_border_color": "C0DEED",
                          |      "profile_sidebar_fill_color": "DDEEF6",
                          |      "profile_text_color": "333333",
                          |      "profile_use_background_image": true,
                          |      "default_profile": true,
                          |      "default_profile_image": false,
                          |      "following": false,
                          |      "follow_request_sent": false,
                          |      "notifications": false,
                          |      "muting": false
                          |    },
                          |    {
                          |      "id": 2960050714,
                          |      "id_str": "2960050714",
                          |      "name": "kovacs lenard",
                          |      "screen_name": "kovacs_lenard",
                          |      "location": "Románia Szilágymegye Szilágyzo",
                          |      "profile_location": null,
                          |      "url": null,
                          |      "description": "",
                          |      "protected": false,
                          |      "followers_count": 1,
                          |      "friends_count": 20,
                          |      "listed_count": 0,
                          |      "created_at": "Sun Jan 04 10:35:34 +0000 2015",
                          |      "favourites_count": 1,
                          |      "utc_offset": null,
                          |      "time_zone": null,
                          |      "geo_enabled": false,
                          |      "verified": false,
                          |      "statuses_count": 1,
                          |      "lang": "hu",
                          |      "contributors_enabled": false,
                          |      "is_translator": false,
                          |      "is_translation_enabled": false,
                          |      "profile_background_color": "C0DEED",
                          |      "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png",
                          |      "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png",
                          |      "profile_background_tile": false,
                          |      "profile_image_url": "http://pbs.twimg.com/profile_images/551699050530369536/UHoRpeSy_normal.jpeg",
                          |      "profile_image_url_https": "https://pbs.twimg.com/profile_images/551699050530369536/UHoRpeSy_normal.jpeg",
                          |      "profile_link_color": "0084B4",
                          |      "profile_sidebar_border_color": "C0DEED",
                          |      "profile_sidebar_fill_color": "DDEEF6",
                          |      "profile_text_color": "333333",
                          |      "profile_use_background_image": true,
                          |      "default_profile": true,
                          |      "default_profile_image": false,
                          |      "following": false,
                          |      "follow_request_sent": false,
                          |      "notifications": false,
                          |      "muting": false
                          |    },
                          |    {
                          |      "id": 2959761230,
                          |      "id_str": "2959761230",
                          |      "name": "Thai Minh Phuong",
                          |      "screen_name": "minhphuongthai",
                          |      "location": "",
                          |      "profile_location": null,
                          |      "url": null,
                          |      "description": "",
                          |      "protected": false,
                          |      "followers_count": 3,
                          |      "friends_count": 32,
                          |      "listed_count": 0,
                          |      "created_at": "Mon Jan 05 14:26:29 +0000 2015",
                          |      "favourites_count": 3,
                          |      "utc_offset": null,
                          |      "time_zone": null,
                          |      "geo_enabled": false,
                          |      "verified": false,
                          |      "statuses_count": 1,
                          |      "lang": "en",
                          |      "contributors_enabled": false,
                          |      "is_translator": false,
                          |      "is_translation_enabled": false,
                          |      "profile_background_color": "C0DEED",
                          |      "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png",
                          |      "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png",
                          |      "profile_background_tile": false,
                          |      "profile_image_url": "http://pbs.twimg.com/profile_images/552109455341395968/soBjm83D_normal.jpeg",
                          |      "profile_image_url_https": "https://pbs.twimg.com/profile_images/552109455341395968/soBjm83D_normal.jpeg",
                          |      "profile_link_color": "0084B4",
                          |      "profile_sidebar_border_color": "C0DEED",
                          |      "profile_sidebar_fill_color": "DDEEF6",
                          |      "profile_text_color": "333333",
                          |      "profile_use_background_image": true,
                          |      "default_profile": true,
                          |      "default_profile_image": false,
                          |      "following": false,
                          |      "follow_request_sent": false,
                          |      "notifications": false,
                          |      "muting": false
                          |    },
                          |    {
                          |      "id": 2276738430,
                          |      "id_str": "2276738430",
                          |      "name": "Veteran Maids, LLC",
                          |      "screen_name": "VeteranMaids",
                          |      "location": "Alexandria, VA",
                          |      "profile_location": null,
                          |      "url": "http://VeteranMaids.com",
                          |      "description": "Veteran Maids, LLC is a Professional Maid & Carpet Cleaning company for both residential and commercial properties.",
                          |      "protected": false,
                          |      "followers_count": 4274,
                          |      "friends_count": 1707,
                          |      "listed_count": 2,
                          |      "created_at": "Sat Jan 04 22:36:51 +0000 2014",
                          |      "favourites_count": 0,
                          |      "utc_offset": null,
                          |      "time_zone": null,
                          |      "geo_enabled": true,
                          |      "verified": false,
                          |      "statuses_count": 121,
                          |      "lang": "en",
                          |      "contributors_enabled": false,
                          |      "is_translator": false,
                          |      "is_translation_enabled": false,
                          |      "profile_background_color": "310573",
                          |      "profile_background_image_url": "http://pbs.twimg.com/profile_background_images/453831537448861696/p2USQJzn.png",
                          |      "profile_background_image_url_https": "https://pbs.twimg.com/profile_background_images/453831537448861696/p2USQJzn.png",
                          |      "profile_background_tile": true,
                          |      "profile_image_url": "http://pbs.twimg.com/profile_images/431233323927498752/iFh9mt5h_normal.png",
                          |      "profile_image_url_https": "https://pbs.twimg.com/profile_images/431233323927498752/iFh9mt5h_normal.png",
                          |      "profile_banner_url": "https://pbs.twimg.com/profile_banners/2276738430/1405776681",
                          |      "profile_link_color": "52545E",
                          |      "profile_sidebar_border_color": "FFFFFF",
                          |      "profile_sidebar_fill_color": "C0DFEC",
                          |      "profile_text_color": "333333",
                          |      "profile_use_background_image": true,
                          |      "default_profile": false,
                          |      "default_profile_image": false,
                          |      "following": false,
                          |      "follow_request_sent": false,
                          |      "notifications": false,
                          |      "muting": false
                          |    },
                          |    {
                          |      "id": 2959714152,
                          |      "id_str": "2959714152",
                          |      "name": "عبدالرحمن",
                          |      "screen_name": "dhoom39025256",
                          |      "location": "",
                          |      "profile_location": null,
                          |      "url": null,
                          |      "description": "",
                          |      "protected": false,
                          |      "followers_count": 4,
                          |      "friends_count": 134,
                          |      "listed_count": 0,
                          |      "created_at": "Mon Jan 05 14:19:31 +0000 2015",
                          |      "favourites_count": 0,
                          |      "utc_offset": null,
                          |      "time_zone": null,
                          |      "geo_enabled": false,
                          |      "verified": false,
                          |      "statuses_count": 0,
                          |      "lang": "ar",
                          |      "contributors_enabled": false,
                          |      "is_translator": false,
                          |      "is_translation_enabled": false,
                          |      "profile_background_color": "C0DEED",
                          |      "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png",
                          |      "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png",
                          |      "profile_background_tile": false,
                          |      "profile_image_url": "http://abs.twimg.com/sticky/default_profile_images/default_profile_3_normal.png",
                          |      "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_3_normal.png",
                          |      "profile_link_color": "0084B4",
                          |      "profile_sidebar_border_color": "C0DEED",
                          |      "profile_sidebar_fill_color": "DDEEF6",
                          |      "profile_text_color": "333333",
                          |      "profile_use_background_image": true,
                          |      "default_profile": true,
                          |      "default_profile_image": true,
                          |      "following": false,
                          |      "follow_request_sent": false,
                          |      "notifications": false,
                          |      "muting": false
                          |    },
                          |    {
                          |      "id": 2962147516,
                          |      "id_str": "2962147516",
                          |      "name": "laurent meunier",
                          |      "screen_name": "laurentmeunie15",
                          |      "location": "",
                          |      "profile_location": null,
                          |      "url": null,
                          |      "description": "",
                          |      "protected": false,
                          |      "followers_count": 3,
                          |      "friends_count": 60,
                          |      "listed_count": 0,
                          |      "created_at": "Mon Jan 05 14:16:39 +0000 2015",
                          |      "favourites_count": 0,
                          |      "utc_offset": -28800,
                          |      "time_zone": "Tijuana",
                          |      "geo_enabled": false,
                          |      "verified": false,
                          |      "statuses_count": 5,
                          |      "lang": "fr",
                          |      "contributors_enabled": false,
                          |      "is_translator": false,
                          |      "is_translation_enabled": false,
                          |      "profile_background_color": "C0DEED",
                          |      "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png",
                          |      "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png",
                          |      "profile_background_tile": false,
                          |      "profile_image_url": "http://pbs.twimg.com/profile_images/552106648450256896/EJ_uMfeN_normal.jpeg",
                          |      "profile_image_url_https": "https://pbs.twimg.com/profile_images/552106648450256896/EJ_uMfeN_normal.jpeg",
                          |      "profile_link_color": "0084B4",
                          |      "profile_sidebar_border_color": "C0DEED",
                          |      "profile_sidebar_fill_color": "DDEEF6",
                          |      "profile_text_color": "333333",
                          |      "profile_use_background_image": true,
                          |      "default_profile": true,
                          |      "default_profile_image": false,
                          |      "following": false,
                          |      "follow_request_sent": false,
                          |      "notifications": false,
                          |      "muting": false
                          |    },
                          |    {
                          |      "id": 46135775,
                          |      "id_str": "46135775",
                          |      "name": "Sven Markschläger",
                          |      "screen_name": "markschlaeger",
                          |      "location": "Berlin, Germany",
                          |      "profile_location": null,
                          |      "url": null,
                          |      "description": "",
                          |      "protected": false,
                          |      "followers_count": 22,
                          |      "friends_count": 264,
                          |      "listed_count": 0,
                          |      "created_at": "Wed Jun 10 15:20:20 +0000 2009",
                          |      "favourites_count": 0,
                          |      "utc_offset": 3600,
                          |      "time_zone": "Paris",
                          |      "geo_enabled": false,
                          |      "verified": false,
                          |      "statuses_count": 0,
                          |      "lang": "en",
                          |      "contributors_enabled": false,
                          |      "is_translator": false,
                          |      "is_translation_enabled": false,
                          |      "profile_background_color": "131516",
                          |      "profile_background_image_url": "http://pbs.twimg.com/profile_background_images/550968824749494272/DOk_jyJR.jpeg",
                          |      "profile_background_image_url_https": "https://pbs.twimg.com/profile_background_images/550968824749494272/DOk_jyJR.jpeg",
                          |      "profile_background_tile": false,
                          |      "profile_image_url": "http://pbs.twimg.com/profile_images/550962973842223104/tg9r2aKF_normal.png",
                          |      "profile_image_url_https": "https://pbs.twimg.com/profile_images/550962973842223104/tg9r2aKF_normal.png",
                          |      "profile_banner_url": "https://pbs.twimg.com/profile_banners/46135775/1420195860",
                          |      "profile_link_color": "131516",
                          |      "profile_sidebar_border_color": "FFFFFF",
                          |      "profile_sidebar_fill_color": "DDEEF6",
                          |      "profile_text_color": "333333",
                          |      "profile_use_background_image": false,
                          |      "default_profile": false,
                          |      "default_profile_image": false,
                          |      "following": false,
                          |      "follow_request_sent": false,
                          |      "notifications": false,
                          |      "muting": false
                          |    },
                          |    {
                          |      "id": 2958779324,
                          |      "id_str": "2958779324",
                          |      "name": "Jdj Jdj",
                          |      "screen_name": "jjdj156",
                          |      "location": "",
                          |      "profile_location": null,
                          |      "url": null,
                          |      "description": "ابوعبدالله",
                          |      "protected": false,
                          |      "followers_count": 14,
                          |      "friends_count": 90,
                          |      "listed_count": 0,
                          |      "created_at": "Sun Jan 04 18:46:30 +0000 2015",
                          |      "favourites_count": 1,
                          |      "utc_offset": null,
                          |      "time_zone": null,
                          |      "geo_enabled": false,
                          |      "verified": false,
                          |      "statuses_count": 2,
                          |      "lang": "ar",
                          |      "contributors_enabled": false,
                          |      "is_translator": false,
                          |      "is_translation_enabled": false,
                          |      "profile_background_color": "C0DEED",
                          |      "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png",
                          |      "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png",
                          |      "profile_background_tile": false,
                          |      "profile_image_url": "http://pbs.twimg.com/profile_images/551812267205881856/0WcgsQpG_normal.jpeg",
                          |      "profile_image_url_https": "https://pbs.twimg.com/profile_images/551812267205881856/0WcgsQpG_normal.jpeg",
                          |      "profile_link_color": "0084B4",
                          |      "profile_sidebar_border_color": "C0DEED",
                          |      "profile_sidebar_fill_color": "DDEEF6",
                          |      "profile_text_color": "333333",
                          |      "profile_use_background_image": true,
                          |      "default_profile": true,
                          |      "default_profile_image": false,
                          |      "following": false,
                          |      "follow_request_sent": false,
                          |      "notifications": false,
                          |      "muting": false
                          |    },
                          |    {
                          |      "id": 2962131838,
                          |      "id_str": "2962131838",
                          |      "name": "uğur kurnaz",
                          |      "screen_name": "ukurnaz1907",
                          |      "location": "",
                          |      "profile_location": null,
                          |      "url": null,
                          |      "description": "",
                          |      "protected": false,
                          |      "followers_count": 10,
                          |      "friends_count": 52,
                          |      "listed_count": 0,
                          |      "created_at": "Mon Jan 05 14:06:43 +0000 2015",
                          |      "favourites_count": 0,
                          |      "utc_offset": null,
                          |      "time_zone": null,
                          |      "geo_enabled": false,
                          |      "verified": false,
                          |      "statuses_count": 1,
                          |      "lang": "tr",
                          |      "contributors_enabled": false,
                          |      "is_translator": false,
                          |      "is_translation_enabled": false,
                          |      "profile_background_color": "C0DEED",
                          |      "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png",
                          |      "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png",
                          |      "profile_background_tile": false,
                          |      "profile_image_url": "http://pbs.twimg.com/profile_images/552105077473689600/G2UzTB6k_normal.jpeg",
                          |      "profile_image_url_https": "https://pbs.twimg.com/profile_images/552105077473689600/G2UzTB6k_normal.jpeg",
                          |      "profile_link_color": "0084B4",
                          |      "profile_sidebar_border_color": "C0DEED",
                          |      "profile_sidebar_fill_color": "DDEEF6",
                          |      "profile_text_color": "333333",
                          |      "profile_use_background_image": true,
                          |      "default_profile": true,
                          |      "default_profile_image": false,
                          |      "following": false,
                          |      "follow_request_sent": false,
                          |      "notifications": false,
                          |      "muting": false
                          |    },
                          |    {
                          |      "id": 492266607,
                          |      "id_str": "492266607",
                          |      "name": "Savaliya amit (AV)",
                          |      "screen_name": "Savaliyaamit46",
                          |      "location": "ahmedabad",
                          |      "profile_location": null,
                          |      "url": null,
                          |      "description": "",
                          |      "protected": false,
                          |      "followers_count": 118,
                          |      "friends_count": 801,
                          |      "listed_count": 0,
                          |      "created_at": "Tue Feb 14 14:40:30 +0000 2012",
                          |      "favourites_count": 5,
                          |      "utc_offset": null,
                          |      "time_zone": null,
                          |      "geo_enabled": true,
                          |      "verified": false,
                          |      "statuses_count": 9,
                          |      "lang": "en",
                          |      "contributors_enabled": false,
                          |      "is_translator": false,
                          |      "is_translation_enabled": false,
                          |      "profile_background_color": "C0DEED",
                          |      "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png",
                          |      "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png",
                          |      "profile_background_tile": false,
                          |      "profile_image_url": "http://pbs.twimg.com/profile_images/546167106870341633/oDxmrGyd_normal.jpeg",
                          |      "profile_image_url_https": "https://pbs.twimg.com/profile_images/546167106870341633/oDxmrGyd_normal.jpeg",
                          |      "profile_banner_url": "https://pbs.twimg.com/profile_banners/492266607/1419051359",
                          |      "profile_link_color": "0084B4",
                          |      "profile_sidebar_border_color": "C0DEED",
                          |      "profile_sidebar_fill_color": "DDEEF6",
                          |      "profile_text_color": "333333",
                          |      "profile_use_background_image": true,
                          |      "default_profile": true,
                          |      "default_profile_image": false,
                          |      "following": false,
                          |      "follow_request_sent": false,
                          |      "notifications": false,
                          |      "muting": false
                          |    },
                          |    {
                          |      "id": 2962128304,
                          |      "id_str": "2962128304",
                          |      "name": "elideangelo correa ",
                          |      "screen_name": "elideangelo22",
                          |      "location": "",
                          |      "profile_location": null,
                          |      "url": null,
                          |      "description": "",
                          |      "protected": false,
                          |      "followers_count": 6,
                          |      "friends_count": 114,
                          |      "listed_count": 0,
                          |      "created_at": "Mon Jan 05 14:03:34 +0000 2015",
                          |      "favourites_count": 0,
                          |      "utc_offset": null,
                          |      "time_zone": null,
                          |      "geo_enabled": false,
                          |      "verified": false,
                          |      "statuses_count": 0,
                          |      "lang": "pt",
                          |      "contributors_enabled": false,
                          |      "is_translator": false,
                          |      "is_translation_enabled": false,
                          |      "profile_background_color": "C0DEED",
                          |      "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png",
                          |      "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png",
                          |      "profile_background_tile": false,
                          |      "profile_image_url": "http://abs.twimg.com/sticky/default_profile_images/default_profile_2_normal.png",
                          |      "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_2_normal.png",
                          |      "profile_link_color": "0084B4",
                          |      "profile_sidebar_border_color": "C0DEED",
                          |      "profile_sidebar_fill_color": "DDEEF6",
                          |      "profile_text_color": "333333",
                          |      "profile_use_background_image": true,
                          |      "default_profile": true,
                          |      "default_profile_image": true,
                          |      "following": false,
                          |      "follow_request_sent": false,
                          |      "notifications": false,
                          |      "muting": false
                          |    },
                          |    {
                          |      "id": 2962024185,
                          |      "id_str": "2962024185",
                          |      "name": "Coda di Tomcat",
                          |      "screen_name": "CodaDiTomcat",
                          |      "location": "Firenze",
                          |      "profile_location": null,
                          |      "url": "http://codatomcat.blogspot.it/",
                          |      "description": "Riflessioni sulle praterie dello sviluppo software",
                          |      "protected": false,
                          |      "followers_count": 2,
                          |      "friends_count": 54,
                          |      "listed_count": 0,
                          |      "created_at": "Mon Jan 05 13:37:11 +0000 2015",
                          |      "favourites_count": 0,
                          |      "utc_offset": null,
                          |      "time_zone": null,
                          |      "geo_enabled": false,
                          |      "verified": false,
                          |      "statuses_count": 2,
                          |      "lang": "it",
                          |      "contributors_enabled": false,
                          |      "is_translator": false,
                          |      "is_translation_enabled": false,
                          |      "profile_background_color": "C0DEED",
                          |      "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png",
                          |      "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png",
                          |      "profile_background_tile": false,
                          |      "profile_image_url": "http://pbs.twimg.com/profile_images/552096612407734272/RwHUx8RM_normal.jpeg",
                          |      "profile_image_url_https": "https://pbs.twimg.com/profile_images/552096612407734272/RwHUx8RM_normal.jpeg",
                          |      "profile_banner_url": "https://pbs.twimg.com/profile_banners/2962024185/1420465187",
                          |      "profile_link_color": "0084B4",
                          |      "profile_sidebar_border_color": "C0DEED",
                          |      "profile_sidebar_fill_color": "DDEEF6",
                          |      "profile_text_color": "333333",
                          |      "profile_use_background_image": true,
                          |      "default_profile": true,
                          |      "default_profile_image": false,
                          |      "following": false,
                          |      "follow_request_sent": false,
                          |      "notifications": false,
                          |      "muting": false
                          |    },
                          |    {
                          |      "id": 62533549,
                          |      "id_str": "62533549",
                          |      "name": "Andre C. S. Araujo",
                          |      "screen_name": "andrecristh",
                          |      "location": "",
                          |      "profile_location": null,
                          |      "url": null,
                          |      "description": "Meu mundo minha vida.",
                          |      "protected": false,
                          |      "followers_count": 7,
                          |      "friends_count": 23,
                          |      "listed_count": 0,
                          |      "created_at": "Mon Aug 03 14:59:57 +0000 2009",
                          |      "favourites_count": 2,
                          |      "utc_offset": -7200,
                          |      "time_zone": "Brasilia",
                          |      "geo_enabled": true,
                          |      "verified": false,
                          |      "statuses_count": 13,
                          |      "lang": "pt",
                          |      "contributors_enabled": false,
                          |      "is_translator": false,
                          |      "is_translation_enabled": false,
                          |      "profile_background_color": "131516",
                          |      "profile_background_image_url": "http://abs.twimg.com/images/themes/theme14/bg.gif",
                          |      "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme14/bg.gif",
                          |      "profile_background_tile": true,
                          |      "profile_image_url": "http://pbs.twimg.com/profile_images/551838098074894336/UrVaQgmo_normal.jpeg",
                          |      "profile_image_url_https": "https://pbs.twimg.com/profile_images/551838098074894336/UrVaQgmo_normal.jpeg",
                          |      "profile_banner_url": "https://pbs.twimg.com/profile_banners/62533549/1420403424",
                          |      "profile_link_color": "009999",
                          |      "profile_sidebar_border_color": "EEEEEE",
                          |      "profile_sidebar_fill_color": "EFEFEF",
                          |      "profile_text_color": "333333",
                          |      "profile_use_background_image": true,
                          |      "default_profile": false,
                          |      "default_profile_image": false,
                          |      "following": false,
                          |      "follow_request_sent": false,
                          |      "notifications": false,
                          |      "muting": false
                          |    }
                          |  ],
                          |  "next_cursor": 1489467234237774933,
                          |  "next_cursor_str": "1489467234237774933",
                          |  "previous_cursor": 0,
                          |  "previous_cursor_str": "0"
                          |} """.stripMargin

        val res = decode[UserArray](json) match {
          case Right(user) => {
            user.users.foreach(println(_))
            true
          }
          case Left(error) => {
            println(error)
            false
          }
        }

      res should be (true)
    }

  }

}
